name: GitHub Actions Demo
on: 
  push:
    branches: [main]
    paths-ignore: '.github/**'
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event:${{ github.event.type }}"
      - run: echo "Branch:${{ github.ref }}"
      - run: ls -a
